(()=>{
const layer=document.getElementById('googleGarden'),mapEl=document.getElementById('googleGardenMap'),msg=document.getElementById('gardenMapMessage');
if(!layer||!mapEl)return;
let map,selfOverlay,selfPos,watchId,lastMode='',roster=[],loading,decorMade=false;const remoteOverlays=new Map(),decor=[];
const state=()=>window.ZooCafeGame?.getState?.(),img=a=>a==='rabbit'?'images/rabbit/rabbit-preview.png':'images/mung-saja-down-2.png';
function say(t){msg.textContent=t;msg.hidden=false} function quiet(){msg.hidden=true}
async function load(){if(window.google?.maps)return true;if(loading)return loading;loading=new Promise((ok,no)=>{const key=window.ZOO_MAPS_DEMO_KEY||window.ZOO_MAPS_API_KEY;if(!key){say('Google Maps 키가 없습니다.');ok(false);return}window.gm_authFailure=()=>say('Google Maps 인증 오류: Demo Key의 웹사이트 허용 주소/API 설정을 확인해 주세요.');window.__z47=()=>ok(true);const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&callback=__z47&v=weekly&language=ko&region=KR&auth_referrer_policy=origin`;s.async=true;s.defer=true;s.onerror=()=>no(new Error('maps load failed'));document.head.appendChild(s)}).catch(e=>{console.error(e);say('Google 지도를 불러오지 못했습니다.');return false});return loading}
function overlay(pos,node,pane='overlayMouseTarget'){class O extends google.maps.OverlayView{onAdd(){this.getPanes()[pane].appendChild(node)}draw(){const p=this.getProjection().fromLatLngToDivPixel(new google.maps.LatLng(pos.lat,pos.lng));node.style.left=p.x+'px';node.style.top=p.y+'px'}onRemove(){node.remove()}setPosition(x){pos=x;this.draw()}}const o=new O();o.setMap(map);return o}
function avatar(a,label,sil=false,me=false){const d=document.createElement('div');d.className='z47-avatar '+(me?'me ':'')+(sil?'silhouette':'');const i=document.createElement('img');i.src=img(a);i.alt='';const n=document.createElement('span');n.textContent=label;d.append(i,n);return d}
function landmark(icon,name){const d=document.createElement('div');d.className='z47-landmark';d.innerHTML=`<b>${icon}</b><span>${name}</span>`;return d}
function addDecor(lat,lng){if(decorMade)return;decorMade=true;const pts=[
 [0.0015,0.0007,'🌳','멍사자 숲'],[-0.0010,0.0013,'☕','주카페 쉼터'],[0.0006,-0.0014,'🐾','친구 광장'],[-0.0015,-0.0008,'🪑','바람 벤치'],[0.0010,-0.0010,'✨','별빛 정원']];
 for(const [a,b,ic,n] of pts)decor.push(overlay({lat:lat+a,lng:lng+b},landmark(ic,n),'overlayMouseTarget'))}
function mine(lat,lng){selfPos={lat,lng};if(!map)return;if(!selfOverlay)selfOverlay=overlay(selfPos,avatar(window.ZOO_USER?.animal||'lion','나',false,true));else selfOverlay.setPosition(selfPos);if(!decorMade)addDecor(lat,lng);map.panTo(selfPos);quiet()}
function sync(){if(!map)return;const me=window.ZOO_USER?.id,seen=new Set();for(const p of roster){if(!p||p.id===me||p.mode!=='nearby'||!Number.isFinite(p.mapLat)||!Number.isFinite(p.mapLon)||!Number.isFinite(p.distanceM)||p.distanceM>1000)continue;seen.add(p.id);const sil=p.distanceM>500,pos={lat:p.mapLat,lng:p.mapLon},label=sil?`??? · 약 ${Math.round(p.distanceM/50)*50}m`:`${p.nickname} · 약 ${Math.round(p.distanceM/10)*10}m`;let o=remoteOverlays.get(p.id);if(!o){o=overlay(pos,avatar(p.animal,label,sil));remoteOverlays.set(p.id,o)}else o.setPosition(pos)}for(const[id,o]of remoteOverlays)if(!seen.has(id)){o.setMap(null);remoteOverlays.delete(id)}}
async function open(){layer.hidden=false;document.body.classList.add('v45-map-screen');say('GPS와 ZOO 정원을 연결하는 중…');if(!(await load()))return;if(!map)map=new google.maps.Map(mapEl,{center:selfPos||{lat:37.5665,lng:126.9780},zoom:17,minZoom:15,maxZoom:19,disableDefaultUI:true,zoomControl:true,gestureHandling:'greedy',clickableIcons:false,styles:[
{elementType:'geometry',stylers:[{color:'#efe1bd'}]},{elementType:'labels.text.fill',stylers:[{color:'#654b36'}]},{elementType:'labels.text.stroke',stylers:[{color:'#fff5dd'}]},{featureType:'poi',elementType:'labels',stylers:[{visibility:'off'}]},{featureType:'poi.business',stylers:[{visibility:'off'}]},{featureType:'poi.park',elementType:'geometry',stylers:[{color:'#b9d79b'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#fff0ca'}]},{featureType:'road',elementType:'geometry.stroke',stylers:[{color:'#d7bc8e'}]},{featureType:'road',elementType:'labels.icon',stylers:[{visibility:'off'}]},{featureType:'transit',elementType:'labels.icon',stylers:[{visibility:'off'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#9ed5dc'}]}]});
 if(navigator.geolocation&&watchId==null)watchId=navigator.geolocation.watchPosition(p=>{mine(p.coords.latitude,p.coords.longitude);window.ZooCafeNet?.sendGeo?.(p.coords.latitude,p.coords.longitude)},e=>say(e.code===1?'휴대폰 위치 권한을 허용해 주세요.':'GPS 위치를 확인하지 못했습니다.'),{enableHighAccuracy:true,maximumAge:3000,timeout:15000});sync()}
function close(){layer.hidden=true;document.body.classList.remove('v45-map-screen');if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null}if(selfOverlay){selfOverlay.setMap(null);selfOverlay=null}for(const o of remoteOverlays.values())o.setMap(null);remoteOverlays.clear();for(const o of decor)o.setMap(null);decor.length=0;decorMade=false}
const h=setInterval(()=>{const g=window.ZooCafeGame;if(!g||g.__v47)return;g.__v47=true;clearInterval(h);const sr=g.setRoster.bind(g),sm=g.setRemote.bind(g);g.setRoster=l=>{roster=Array.isArray(l)?l:[];sr(l);sync()};g.setRemote=p=>{sm(p);if(p){const i=roster.findIndex(x=>x.id===p.id);i>=0?roster[i]={...roster[i],...p}:roster.push(p);sync()}}},50);
setInterval(()=>{const m=state()?.mode||'';if(m!==lastMode){lastMode=m;m==='nearby'?open():close()}},100);
})();