(()=>{
const layer=document.getElementById('googleGarden'),mapEl=document.getElementById('googleGardenMap'),msg=document.getElementById('gardenMapMessage');
if(!layer||!mapEl)return;
let map,selfOverlay,center,watchId,lastMode='',roster=[],loading,decorMade=false;const remoteOverlays=new Map(),decor=[],mapBubbles=new Map();
const FIELD_W=2880,FIELD_H=1800,HALF_M=500; // approx 1 km x 1 km fixed garden
const state=()=>window.ZooCafeGame?.getState?.(),img=a=>a==='rabbit'?'images/rabbit/rabbit-preview.png':'images/mung-saja-down-2.png';
function say(t){msg.textContent=t;msg.hidden=false}function quiet(){msg.hidden=true}
async function load(){if(window.google?.maps)return true;if(loading)return loading;loading=new Promise((ok,no)=>{const key=window.ZOO_MAPS_DEMO_KEY||window.ZOO_MAPS_API_KEY;if(!key){say('Google Maps 키가 없습니다.');ok(false);return}window.gm_authFailure=()=>say('Google Maps 인증 설정을 확인해 주세요.');window.__z49=()=>ok(true);const x=document.createElement('script');x.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(key)}&callback=__z49&v=weekly&language=ko&region=KR&auth_referrer_policy=origin`;x.async=true;x.defer=true;x.onerror=()=>no(new Error('maps load failed'));document.head.appendChild(x)}).catch(e=>{console.error(e);say('Google 지도를 불러오지 못했습니다.');return false});return loading}
function overlay(pos,node,pane='overlayMouseTarget'){class O extends google.maps.OverlayView{onAdd(){this.getPanes()[pane].appendChild(node)}draw(){const p=this.getProjection().fromLatLngToDivPixel(new google.maps.LatLng(pos.lat,pos.lng));node.style.left=p.x+'px';node.style.top=p.y+'px'}onRemove(){node.remove()}setPosition(x){pos=x;this.draw()}}const o=new O();o.setMap(map);return o}
function avatar(a,label,me=false){const d=document.createElement('div');d.className='z47-avatar '+(me?'me':'');const i=document.createElement('img');i.src=img(a);i.alt='';const n=document.createElement('span');n.textContent=label;d.append(i,n);return d}
function landmark(icon,name){const d=document.createElement('div');d.className='z47-landmark';d.innerHTML=`<b>${icon}</b><span>${name}</span>`;return d}
function xyToLatLng(x,y){if(!center)return null;const north=(HALF_M-(y/FIELD_H)*(HALF_M*2)),east=((x/FIELD_W)*(HALF_M*2)-HALF_M);const lat=center.lat+north/111320,lng=center.lng+east/(111320*Math.cos(center.lat*Math.PI/180));return{lat,lng}}
function addDecor(){if(decorMade||!center)return;decorMade=true;for(const [x,y,ic,n]of[[2050,470,'🌳','멍사자 숲'],[2250,1270,'☕','주카페 쉼터'],[720,690,'🐾','친구 광장'],[850,1370,'🪑','바람 벤치'],[1570,380,'✨','별빛 정원']])decor.push(overlay(xyToLatLng(x,y),landmark(ic,n)))}
function updateSelf(){if(!map||!center)return;const p=window.ZooCafeGame?.getGardenPlayer?.()||state();if(!p)return;const pos=xyToLatLng(p.x,p.y);if(!selfOverlay)selfOverlay=overlay(pos,avatar(window.ZOO_USER?.animal||'lion','나',true));else selfOverlay.setPosition(pos)}
function sync(){if(!map||!center)return;const me=window.ZOO_USER?.id,seen=new Set();for(const p of roster){if(!p||p.id===me||p.mode!=='nearby'||!Number.isFinite(p.distanceM)||p.distanceM>1000)continue;seen.add(p.id);const pos=xyToLatLng(p.x,p.y),label=p.nickname;let o=remoteOverlays.get(p.id);if(!o){o=overlay(pos,avatar(p.animal,label));remoteOverlays.set(p.id,o)}else o.setPosition(pos)}for(const[id,o]of remoteOverlays)if(!seen.has(id)){o.setMap(null);remoteOverlays.delete(id)}}
function showMapBubble(id,text,me=false){if(!map||!center||!text)return;let p=me?(window.ZooCafeGame?.getGardenPlayer?.()||state()):roster.find(x=>x.id===id);if(!p)return;const pos=xyToLatLng(p.x,p.y),old=mapBubbles.get(id);if(old)old.setMap(null);const d=document.createElement('div');d.className='z48-map-bubble';d.textContent=String(text).slice(0,80);const o=overlay(pos,d,'floatPane');mapBubbles.set(id,o);setTimeout(()=>{if(mapBubbles.get(id)===o){o.setMap(null);mapBubbles.delete(id)}},5200)}
window.addEventListener('zoo-map-chat',e=>showMapBubble(e.detail?.id,e.detail?.text,!!e.detail?.me));
async function open(){layer.hidden=false;document.body.classList.add('v45-map-screen');say('1km ZOO 정원을 준비하는 중…');if(!(await load()))return;
 const start=pos=>{center={lat:pos.coords.latitude,lon:pos.coords.longitude};if(!map)map=new google.maps.Map(mapEl,{center,zoom:15,minZoom:15,maxZoom:15,disableDefaultUI:true,gestureHandling:'none',keyboardShortcuts:false,clickableIcons:false,styles:[{elementType:'labels',stylers:[{visibility:'off'}]},{featureType:'poi',elementType:'labels',stylers:[{visibility:'off'}]},{featureType:'poi.business',stylers:[{visibility:'off'}]},{featureType:'poi.park',elementType:'geometry',stylers:[{color:'#b9d79b'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#fff0ca'}]},{featureType:'road',elementType:'geometry.stroke',stylers:[{color:'#d7bc8e'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#9ed5dc'}]},{elementType:'geometry',stylers:[{color:'#efe1bd'}]}]});window.ZooCafeNet?.sendGeo?.(center.lat,center.lon);addDecor();updateSelf();sync();quiet()};
 if(navigator.geolocation)navigator.geolocation.getCurrentPosition(start,e=>say(e.code===1?'휴대폰 위치 권한을 허용해 주세요.':'GPS 위치를 확인하지 못했습니다.'),{enableHighAccuracy:true,maximumAge:10000,timeout:15000});
}
function close(){layer.hidden=true;document.body.classList.remove('v45-map-screen');if(selfOverlay){selfOverlay.setMap(null);selfOverlay=null}for(const o of remoteOverlays.values())o.setMap(null);remoteOverlays.clear();for(const o of decor)o.setMap(null);decor.length=0;for(const o of mapBubbles.values())o.setMap(null);mapBubbles.clear();decorMade=false;center=null;map=null;mapEl.innerHTML=''}
const h=setInterval(()=>{const g=window.ZooCafeGame;if(!g||g.__v49)return;g.__v49=true;clearInterval(h);const sr=g.setRoster.bind(g),sm=g.setRemote.bind(g);g.setRoster=l=>{roster=Array.isArray(l)?l:[];sr(l);sync()};g.setRemote=p=>{sm(p);if(p){const i=roster.findIndex(x=>x.id===p.id);i>=0?roster[i]={...roster[i],...p}:roster.push(p);sync()}}},50);
setInterval(()=>{const m=state()?.mode||'';if(m!==lastMode){lastMode=m;m==='nearby'?open():close()}if(m==='nearby'){updateSelf();sync()}},80);
})();