(()=>{
const list=document.querySelector('.player-list'), badge=document.querySelector('.online'), note=document.querySelector('.players-note');
let ws=null,lastSent=0,lastKey='',reconnectTimer=null;
const token=()=>sessionStorage.getItem('zoocafe_token')||'';
function render(players=[]){const me=window.ZOO_USER;const sorted=[...players].sort((a,b)=>(a.id===me?.id?-1:b.id===me?.id?1:0));badge.textContent=String(sorted.length);list.innerHTML=sorted.map(p=>`<button class="player-row ${p.id===me?.id?'me':''}" type="button"><img src="images/mung-saja-down-2.png" alt=""><span><b>${esc(p.nickname)}</b><small>${p.id===me?.id?'나 · ':''}${({cafe:'카페 내부',bookshop:'숲속 책방',workshop:'공방',lodge:'동물회관',nearby:(p.distanceM==null?'내 주변 광장':`내 주변 · 약 ${p.distanceM}m`)}[p.mode]||'ZOO:CAFE 광장')}</small></span><i>●</i></button>`).join('');note.textContent=ws&&ws.readyState===1?'실시간 서버 연결됨 · 같은 장소의 접속자입니다.':'서버에 다시 연결하는 중...';}
function esc(s){const d=document.createElement('div');d.textContent=String(s||'');return d.innerHTML}
function connect(){if(!window.ZOO_USER||!token())return;clearTimeout(reconnectTimer);const proto=location.protocol==='https:'?'wss:':'ws:';ws=new WebSocket(`${proto}//${location.host}`);window.ZooCafeNet.connected=false;
 ws.addEventListener('open',()=>ws.send(JSON.stringify({type:'auth',token:token()})));
 ws.addEventListener('message',e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='ready'){window.ZooCafeNet.connected=true;note.textContent='실시간 서버 연결됨';window.ZooCafeNet.tick(true)}else if(m.type==='roster'){window.ZooCafeGame?.setRoster(m.players);render(m.players)}else if(m.type==='state'){window.ZooCafeGame?.setRemote(m.player)}else if(m.type==='npc_thinking'){window.ZooCafeAI?.receiveThinking?.(m)}else if(m.type==='npc_reply'){window.ZooCafeAI?.receiveReply?.(m)}else if(m.type==='npc_autonomous_state'){window.ZooCafeAI?.receiveAutonomousState?.(m.life)}else if(m.type==='npc_autonomous_turn'){window.ZooCafeAI?.receiveAutonomousTurn?.(m.event,m.actors)}else if(m.type==='cafe_scene'){window.ZooCafeScene?.apply?.(m.sceneId)}else if(m.type==='cafe_event'){window.ZooCafeCafeEvent?.apply?.(m.event)}else if(m.type==='chat'){window.ZooCafeGame?.remoteChat(m)}});
 ws.addEventListener('close',()=>{window.ZooCafeNet.connected=false;window.ZooCafeGame?.clearRemotes();render([]);reconnectTimer=setTimeout(connect,1800)});ws.addEventListener('error',()=>{});
}
window.ZooCafeNet={connected:false,tick(force=false){if(!this.connected||!ws||ws.readyState!==1)return;const now=performance.now();const s=window.ZooCafeGame?.getState();if(!s)return;const key=[s.mode,Math.round(s.x),Math.round(s.y),s.dir,s.frame,s.moving].join('|');if(!force&&key===lastKey&&now-lastSent<1000)return;if(!force&&now-lastSent<70)return;lastKey=key;lastSent=now;ws.send(JSON.stringify({type:'state',...s}))},sendChat(text){if(this.connected&&ws?.readyState===1)ws.send(JSON.stringify({type:'chat',text}))},sendNpcChat(npcId,text){if(this.connected&&ws?.readyState===1)ws.send(JSON.stringify({type:'npc_chat',npcId,text}))}};
window.addEventListener('zoocafe-auth',connect);if(window.ZOO_USER)connect();
})();