(()=>{
 const params=new URLSearchParams(location.search),incoming=[params.get('share'),params.get('url'),params.get('text')].filter(Boolean).join(' ').trim();
 const ui=document.createElement('aside');ui.id='shareFlow';ui.hidden=true;
 ui.innerHTML='<header><img src="images/mung-saja-down-2.png" alt="멍사자"><div><strong>멍사자와 함께 살펴볼까?</strong><small>링크를 가져와서 이야기와 의뢰로 이어 보세요.</small></div><button id="shareClose" aria-label="닫기">×</button></header><label>링크 또는 관심사<input id="shareLink" placeholder="영상·게시글 링크나 궁금한 내용을 붙여 넣어 주세요"></label><label>무엇이 궁금해?<input id="shareQuestion" placeholder="예: 이런 분위기의 애니를 추천받고 싶어"></label><div class="share-actions"><button id="shareFind">🔎 찾아보기</button><button id="shareAsk">💬 사람에게 묻기</button><button id="shareQuest">📜 의뢰 만들기</button></div><div id="shareInfo" role="status"></div><div id="shareMore" hidden><label>관심사 건물<select id="shareTopic"><option value="bookshop">애니 이야기관</option><option value="workshop">게임 길드</option><option value="lodge">생활 정보관</option></select></label><button id="shareEnter">건물로 이동해 질문하기</button></div>';
 document.body.append(ui);const $=s=>ui.querySelector(s),link=$('#shareLink'),question=$('#shareQuestion'),info=$('#shareInfo'),more=$('#shareMore');
 const token=()=>(localStorage.getItem('zoocafe_token')||sessionStorage.getItem('zoocafe_token'));
 const source=()=>{try{const u=new URL(link.value.trim());return /^https?:$/.test(u.protocol)?u.href:''}catch{return ''}};
 const query=()=>question.value.trim()||((link.value.trim()&&!source())?link.value.trim():'');
 function show(t){info.replaceChildren();info.append(document.createTextNode(t))}
 function addLink(label,url){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=label;info.append(document.createElement('br'),a)}
 function showUi(){ui.hidden=false}function cleanUrl(){if(!location.search)return;history.replaceState(null,'',location.pathname+location.hash)}
 $('#shareClose').onclick=()=>{ui.hidden=true;cleanUrl()};
 function openFromShare(){if(!window.ZOO_USER)return;const raw=params.get('text')||'',title=params.get('title')||'',embedded=(raw+' '+title).match(/https?:\/\/[^\s<>]+/i)?.[0]||'';link.value=params.get('url')||params.get('share')||embedded;question.value=(raw.replace(embedded,'').trim()||title.replace(embedded,'').trim()).slice(0,220);if(incoming||title)showUi();const intent=params.get('intent');if(intent==='ask')$('#shareAsk').click();if(intent==='quest')$('#shareQuest').click()}
 $('#shareFind').onclick=async()=>{const term=query();if(!term){show('궁금한 내용이나 검색어를 입력해 줘. 링크만으로 영상 내용을 확정할 수 없어서, 어떤 점이 궁금한지도 알려 줘.');return}show('멍사자와 검색할 자료를 열어 볼게. 결과는 직접 확인해 줘.');addLink('네이버에서 찾아보기','https://search.naver.com/search.naver?query='+encodeURIComponent(term));addLink('구글에서 찾아보기','https://www.google.com/search?q='+encodeURIComponent(term));if(source())addLink('원본 열기',source());
  if(!token())return;try{const response=await fetch('/api/share-assist',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token()},body:JSON.stringify({question:term,url:source()})});const data=await response.json();if(!response.ok)throw Error(data.error);const p=document.createElement('p');p.textContent='멍사자: '+data.reply+(data.ai?'':' (AI 연결 전 기본 응답)');info.prepend(p)}catch(e){const p=document.createElement('p');p.textContent=e.message||'멍사자에게 연결하지 못했어.';info.prepend(p)}};
 $('#shareAsk').onclick=()=>{more.hidden=false;$('#shareEnter').textContent='건물로 이동해 채팅하기';show('관심사에 맞는 건물로 이동할게. 지금 있는 사람과 채팅하고, 사람이 없으면 질문 카드를 남길 수 있어.')};
 $('#shareQuest').onclick=()=>{if(!token()){show('로그인한 뒤 의뢰를 만들 수 있어.');return}const title=query();if(title.length<5){show('의뢰로 만들 질문을 5자 이상 적어 줘.');return}ui.hidden=true;document.getElementById('questOverlay').hidden=false;document.querySelector('#questForm [name="question"]').value=title.slice(0,140);document.querySelector('#questForm [name="details"]').value=(source()?'원본 링크: '+source():'').slice(0,1500);document.querySelector('#questForm [name="details"]').focus();cleanUrl()};
 $('#shareEnter').onclick=()=>{const room=$('#shareTopic').value;if(!window.ZooCafeEnterTopic?.(room)){show('로그인 후 다시 시도해 줘.');return}ui.hidden=true;cleanUrl();setTimeout(()=>{document.getElementById('buildingToggle')?.click();const input=document.getElementById('buildingQuestion');if(input)input.value=[query(),source()].filter(Boolean).join(' · ').slice(0,300)},650)};
 const launch=document.createElement('button');launch.id='shareLaunch';launch.type='button';launch.textContent='🦁 링크 가져오기';launch.onclick=showUi;document.body.append(launch);
 window.addEventListener('zoocafe-auth',openFromShare);if(window.ZOO_USER)openFromShare();
 if('serviceWorker'in navigator)navigator.serviceWorker.register('/share-sw.js').catch(()=>{});
})();
